# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import iharp_query_processor_pb2 as iharp__query__processor__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in iharp_query_processor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DBNodeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRaster = channel.unary_unary(
                '/DBNode/GetRaster',
                request_serializer=iharp__query__processor__pb2.RasterRequest.SerializeToString,
                response_deserializer=iharp__query__processor__pb2.RasterResponse.FromString,
                _registered_method=True)


class DBNodeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRaster(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DBNodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRaster': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRaster,
                    request_deserializer=iharp__query__processor__pb2.RasterRequest.FromString,
                    response_serializer=iharp__query__processor__pb2.RasterResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DBNode', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('DBNode', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DBNode(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRaster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DBNode/GetRaster',
            iharp__query__processor__pb2.RasterRequest.SerializeToString,
            iharp__query__processor__pb2.RasterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
